In [10]:
%load_ext autoreload
%autoreload 2

import numpy as np
import gymnasium as gym
from gymnasium import spaces
import wcst_gym
from wcst_gym.n_hot_observation import NHotObservation
from wcst_session import WcstSession


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
sess = WcstSession(1, 0)
env = gym.make("WcstSession-v0", wcst_session=sess)

In [12]:
env.reset(seed=None)

(array([[ 3,  5, 10],
        [ 2,  6, 11],
        [ 1,  7,  8],
        [ 0,  4,  9]]),
 {'current_rule': 9})

In [13]:
env.observation_space.shape

(4, 3)

In [14]:
env.step(3)

(array([[ 3,  5, 10],
        [ 1,  4, 11],
        [ 0,  6,  9],
        [ 2,  7,  8]]),
 1,
 False,
 False,
 {'current_rule': 9})

In [15]:
env.step(1)

(array([[ 3,  7,  9],
        [ 2,  4, 10],
        [ 1,  5, 11],
        [ 0,  6,  8]]),
 0,
 False,
 False,
 {'current_rule': 9})

In [16]:
env.step(2)

(array([[ 3,  7,  9],
        [ 2,  5,  8],
        [ 1,  4, 11],
        [ 0,  6, 10]]),
 0,
 False,
 False,
 {'current_rule': 9})

In [17]:
env = NHotObservation(env)

In [18]:
env.reset()

(array([[0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.]]),
 {'current_rule': 8})