In [18]:
%load_ext autoreload
%autoreload 2

import numpy as np
import gymnasium as gym
from gymnasium import spaces
import wcst_gym
from wcst_session import WcstSession


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [19]:
sess = WcstSession(1, 0)
env = gym.make("WcstSession-v0", wcst_session=sess)

In [21]:
env.reset(seed=None)

(array([[ 1,  5, 10],
        [ 0,  6, 11],
        [ 3,  4,  8],
        [ 2,  7,  9]]),
 {'current_rule': 8})

In [22]:
env.step(3)

(array([[ 3,  7,  8],
        [ 0,  5,  9],
        [ 2,  4, 10],
        [ 1,  6, 11]]),
 0,
 False,
 False,
 {'current_rule': 8})

In [23]:
env.step(1)

(array([[ 2,  5,  9],
        [ 0,  6, 11],
        [ 1,  4,  8],
        [ 3,  7, 10]]),
 0,
 False,
 False,
 {'current_rule': 8})

In [24]:
env.step(2)

(array([[ 1,  7,  9],
        [ 2,  4, 11],
        [ 3,  6,  8],
        [ 0,  5, 10]]),
 1,
 False,
 False,
 {'current_rule': 8})